# 1. Adatbázis fájlba mentése (a projekt mappáján belül egy 'adatbazis' nevű mappába)
spring.datasource.url=jdbc:h2:file:./adatbazis/raktardb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. H2 Konzol engedélyezése
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Hibernate beállítások (update: nem törli a táblákat, csak frissíti, ha újat írsz)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true

# 4. Kikapcsoljuk az automatikus adatfeltöltést (hogy ne próbálja meg minden induláskor újra beszúrni ugyanazt)
spring.sql.init.mode=never

spring.banner.location= classpath:banner.txt

#Nagyobb képek feltöltése profilhoz
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=10MB
server.tomcat.max-http-form-post-size=10MB

spring.security.oauth2.client.registration.google.client-id=clientid
spring.security.oauth2.client.registration.google.client-secret=clientsecret